# Generated by Django 5.0.3 on 2024-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
